-- Spring Boot 시작시 자동 실행되는 초기 데이터

-- Menu 테이블 기본 데이터
INSERT IGNORE INTO
    menu (
        id,
        name,
        type,
        url,
        display_position,
        visible,
        sort_order,
        created_at,
        updated_at
    )
VALUES (
        1,
        '공지사항',
        'BOARD',
        '/bbs/notice',
        'HEADER',
        1,
        1,
        NOW(),
        NOW()
    ),
    (
        2,
        '뉴스/보도자료',
        'BOARD',
        '/bbs/news',
        'HEADER',
        1,
        2,
        NOW(),
        NOW()
    ),
    (
        3,
        'IR',
        'BOARD',
        '/bbs/ir',
        'HEADER',
        1,
        3,
        NOW(),
        NOW()
    );

-- BBS_MASTER 테이블 기본 데이터
INSERT IGNORE INTO
    bbs_master (
        BBS_ID,
        BBS_NAME,
        SKIN_TYPE,
        READ_AUTH,
        WRITE_AUTH,
        ADMIN_AUTH,
        DISPLAY_YN,
        SORT_ORDER,
        NOTICE_YN,
        PUBLISH_YN,
        ATTACHMENT_YN,
        ATTACHMENT_LIMIT,
        ATTACHMENT_SIZE,
        CREATED_AT,
        UPDATED_AT
    )
VALUES (
        1,
        '공지사항',
        'BASIC',
        'ALL',
        'ADMIN',
        'ADMIN',
        'Y',
        'D',
        'Y',
        'Y',
        'Y',
        5,
        20,
        NOW(),
        NOW()
    ),
    (
        2,
        '뉴스/보도자료',
        'PRESS',
        'ALL',
        'ADMIN',
        'ADMIN',
        'Y',
        'D',
        'N',
        'Y',
        'Y',
        10,
        50,
        NOW(),
        NOW()
    ),
    (
        3,
        'IR',
        'BASIC',
        'ALL',
        'ADMIN',
        'ADMIN',
        'Y',
        'D',
        'N',
        'Y',
        'Y',
        10,
        100,
        NOW(),
        NOW()
    );